use cgmath::{Matrix4, Point3, Quaternion, Vector2, Vector3};
use engine::{
    assets::asset_cache::AssetCache,
    audio::AudioContext,
    scene::{SceneObject, light::SpotLight},
};
use serde::{Deserialize, Serialize};
use shipyard::{EntityId, World};
use std::any::Any;

use crate::{
    GameOptions,
    input_context::InputContext,
    mission::GlobalContext,
    quest_info::QuestInfo,
    scripts::{Effect, GlobalEffect},
    time::Time,
};

#[derive(Clone, Debug)]
pub struct AmbientAudioState {
    pub player_position: Vector3<f32>,
    pub music_cue: Option<String>,
    pub environmental_cue: Option<String>,
    pub ambient_emitters: Vec<(EntityId, Vector3<f32>, String)>,
}

/// Abstract game scene that can be rendered and updated
/// Supports missions, cutscenes, UI screens, debug scenes, etc.
pub trait GameScene {
    /// Main update that handles all scene-specific logic including:
    /// - Player movement and physics
    /// - Collision handling
    /// - Entity updates
    /// - Input processing
    /// Returns effects for the Game layer to process
    fn update(
        &mut self,
        time: &Time,
        input_context: &InputContext,
        asset_cache: &mut AssetCache,
        game_options: &GameOptions,
        command_effects: Vec<Effect>,
    ) -> Vec<Effect>;

    /// Main render pass - returns scene objects and camera position/rotation
    fn render(
        &mut self,
        asset_cache: &mut AssetCache,
        options: &GameOptions,
    ) -> (Vec<SceneObject>, Vector3<f32>, Quaternion<f32>);

    /// VR-specific per-eye rendering
    fn render_per_eye(
        &mut self,
        _asset_cache: &mut AssetCache,
        _view: Matrix4<f32>,
        _projection: Matrix4<f32>,
        _screen_size: Vector2<f32>,
        _options: &GameOptions,
    ) -> Vec<SceneObject> {
        Vec::new()
    }

    /// Finalization step after rendering
    fn finish_render(
        &mut self,
        _asset_cache: &mut AssetCache,
        _view: Matrix4<f32>,
        _projection: Matrix4<f32>,
        _screen_size: Vector2<f32>,
    ) {
    }

    /// Process effects generated by scene update
    fn handle_effects(
        &mut self,
        _effects: Vec<Effect>,
        _global_context: &GlobalContext,
        _game_options: &GameOptions,
        _asset_cache: &mut AssetCache,
        _audio_context: &mut AudioContext<EntityId, String>,
    ) -> Vec<GlobalEffect> {
        Vec::new()
    }

    /// Whether this scene wants a 2D mouse cursor (e.g. a menu). Flat runtimes
    /// show the OS cursor and populate `InputContext::pointer` when true; by
    /// default scenes capture the mouse for look.
    fn wants_pointer(&self) -> bool {
        false
    }

    /// Whether the player's collider is currently crouched (the *actual*
    /// physics state - stand-up can be refused for lack of headroom). Drives
    /// the crouch-aware camera height; non-mission scenes have no player.
    fn player_is_crouched(&self) -> bool {
        false
    }

    /// Get lighting information for VR enhancement
    fn get_hand_spotlights(&self, options: &GameOptions) -> Vec<SpotLight>;

    /// Access to the ECS world (required for most game systems)
    fn world(&self) -> &World;

    /// Scene identification
    fn scene_name(&self) -> &str;

    /// Quest information access (returns current quest state from world)
    fn quest_info(&self) -> QuestInfo {
        self.world()
            .borrow::<shipyard::UniqueView<QuestInfo>>()
            .map(|q| q.clone())
            .unwrap_or_else(|_| QuestInfo::new())
    }

    /// Optional ambient audio information for the scene
    fn ambient_audio_state(&self) -> Option<AmbientAudioState> {
        None
    }

    /// Queue an entity to be triggered after scripts are initialized
    /// This is used for delayed entity triggering during level transitions
    fn queue_entity_trigger(&mut self, entity_name: String) {
        // Default implementation for scenes that don't support entity triggering
        let _ = entity_name;
    }

    /// Downcast to Any for debugging purposes
    fn as_any(&self) -> Option<&dyn Any> {
        None
    }

    /// Downcast to Any (mutable) for debugging purposes
    fn as_any_mut(&mut self) -> Option<&mut dyn Any> {
        None
    }

    /// Expose this scene's debug/introspection interface, if it has one.
    ///
    /// Implemented by full missions and by the debug scenes (which forward to
    /// their inner `MissionCore`), so the debug runtime's HTTP endpoints work
    /// against `debug_*` scenes too.
    fn as_debuggable(&self) -> Option<&dyn DebuggableScene> {
        None
    }

    /// Mutable variant of [`as_debuggable`].
    fn as_debuggable_mut(&mut self) -> Option<&mut dyn DebuggableScene> {
        None
    }
}

// ============================================================================
// Debug Scene Trait and Support Types for Remote Debugging
// ============================================================================

/// Summary information about an entity for debug listing
#[derive(Debug, Serialize, Clone)]
pub struct DebugEntitySummary {
    pub id: i32,
    pub name: String,
    pub template_id: i32,
    pub position: [f32; 3],
    pub distance: f32,
    pub script_count: usize,
    pub link_count: usize,
}

/// Detailed information about an entity for debug inspection
#[derive(Debug, Serialize, Clone)]
pub struct DebugEntityDetail {
    pub entity_id: i32,
    pub name: String,
    pub template_id: i32,
    pub position: [f32; 3],
    pub rotation: [f32; 4], // quaternion
    pub inheritance_chain: Vec<String>,
    pub properties: Vec<DebugPropertyInfo>,
    pub outgoing_links: Vec<DebugLinkInfo>,
    pub incoming_links: Vec<DebugLinkInfo>,
}

/// Property information for debug display
#[derive(Debug, Serialize, Clone)]
pub struct DebugPropertyInfo {
    pub name: String,
    pub value: String,
}

/// Link information for debug display
#[derive(Debug, Serialize, Clone)]
pub struct DebugLinkInfo {
    pub link_type: String,
    pub target_id: i32,
    pub target_name: String,
}

/// Raycast hit result for debug queries
#[derive(Debug, Serialize, Clone)]
pub struct DebugRayHit {
    pub hit: bool,
    pub hit_point: Option<[f32; 3]>,
    pub hit_normal: Option<[f32; 3]>,
    pub distance: Option<f32>,
    pub entity_id: Option<i32>,
    pub entity_name: Option<String>,
    pub collision_group: Option<String>,
    pub is_sensor: bool,
}

/// Raycast mask for collision group filtering
#[derive(Debug, Clone)]
pub struct RaycastMask {
    pub groups: Vec<String>,
}

impl RaycastMask {
    pub fn new(groups: Vec<String>) -> Self {
        Self { groups }
    }

    pub fn all() -> Self {
        Self {
            groups: vec![
                "world".to_string(),
                "entity".to_string(),
                "selectable".to_string(),
                "player".to_string(),
                "ui".to_string(),
                "hitbox".to_string(),
                "raycast".to_string(),
            ],
        }
    }
}

/// Summary information about a physics body for debug listing
#[derive(Debug, Serialize, Clone)]
pub struct DebugPhysicsBodySummary {
    pub body_id: u32,
    pub entity_id: Option<i32>,
    pub entity_name: Option<String>,
    pub body_type: String, // "dynamic", "static", "kinematic"
    pub position: [f32; 3],
    pub rotation: [f32; 4], // quaternion
    pub mass: Option<f32>,
    pub velocity: [f32; 3],
    pub angular_velocity: [f32; 3],
    pub collision_groups: Vec<String>,
    pub is_sensor: bool,
    pub is_enabled: bool,
    pub is_sleeping: bool,
}

/// Detailed information about a physics body for debug inspection
#[derive(Debug, Serialize, Clone)]
pub struct DebugPhysicsBodyDetail {
    pub body_id: u32,
    pub entity_id: Option<i32>,
    pub entity_name: Option<String>,
    pub body_type: String,
    pub position: [f32; 3],
    pub rotation: [f32; 4], // quaternion
    pub linear_velocity: [f32; 3],
    pub angular_velocity: [f32; 3],
    pub mass: Option<f32>,
    pub center_of_mass: [f32; 3],
    pub moment_of_inertia: Option<[f32; 3]>,
    pub gravity_scale: f32,
    pub linear_damping: f32,
    pub angular_damping: f32,
    pub collision_groups: Vec<String>,
    pub is_sensor: bool,
    pub is_enabled: bool,
    pub is_sleeping: bool,
    pub contact_count: usize,
}

/// Per-ragdoll quality/settle metrics for the verification harness.
#[derive(Debug, Serialize, Clone)]
pub struct DebugRagdollMetrics {
    pub entity_id: i32,
    pub body_count: usize,
    pub max_linear_speed: f32,
    pub max_angular_speed: f32,
    pub min_y: f32,
    pub max_nonadjacent_overlap: f32,
    pub max_drift: f32,
}

/// One joint's state, for ragdoll diagnostics. `separation` and the impulses
/// staying non-zero at rest mean the constraint can't be satisfied.
#[derive(Debug, Serialize, Clone)]
pub struct DebugPhysicsJoint {
    pub body1_id: u32,
    pub body2_id: u32,
    /// `"impulse"` or `"multibody"` - which joint set this came from.
    pub joint_type: String,
    /// Skeleton joint id each body represents, if it's a ragdoll body.
    pub bone1: Option<u32>,
    pub bone2: Option<u32>,
    pub anchor1: [f32; 3],
    pub anchor2: [f32; 3],
    pub separation: f32,
    /// Constraint impulses this step. Rapier does not expose these for
    /// multibody links, so they read 0 there.
    pub linear_impulse: f32,
    pub angular_impulse: f32,
}

/// A malformed collider found by the physics audit: an AABB with NaN/inf
/// bounds, zero/negative extent, or extreme coordinates. Bad AABBs poison
/// physics queries (garbage raycasts; a debug-build parry3d overflow), so this
/// is surfaced for any level on demand.
#[derive(Debug, Serialize, Clone)]
pub struct DebugColliderIssue {
    pub entity_id: Option<i32>,
    pub entity_name: Option<String>,
    /// "non_finite" | "degenerate" | "extreme".
    pub kind: String,
    pub aabb_min: [f32; 3],
    pub aabb_max: [f32; 3],
    pub is_sensor: bool,
}

/// A single quest bit (objective flag): its name, a friendly 3-state `value`
/// ("unknown"/"incomplete"/"complete"), and the exact raw `bits`. `value` is a
/// projection (COMPLETE takes precedence), so a rare combined flag (e.g.
/// INCOMPLETE|COMPLETE = 3) reads as "complete" - use `bits` when the exact
/// value matters, since scripts compare quest bits by raw value.
#[derive(Debug, Serialize, Clone)]
pub struct DebugQuestBit {
    pub name: String,
    pub value: String,
    pub bits: u32,
}

/// A single item the player carries: its entity id, name (if any), and where
/// it is held - "inventory" (backpack), "left_hand", or "right_hand".
#[derive(Debug, Serialize, Clone)]
pub struct DebugInventoryItem {
    pub entity_id: i32,
    pub name: Option<String>,
    pub location: String,
}

/// Snapshot of the flat-mode UI state for debug introspection (`GET /v1/ui`).
/// `mode` is "shooter" (mouse-look, no cursor) or "use" (cursor-driven
/// metagame UI, the original game's Tab mode). `active_panel` is the
/// object-bound MFD panel opened by frobbing a GUI-bearing entity (keypad,
/// container, ...), with its clickable elements - see `projects/flat-ui.md`.
#[derive(Debug, Serialize, Clone)]
pub struct DebugUiState {
    pub mode: String,
    pub active_panel: Option<DebugUiPanel>,
    /// The top-docked inventory strip (Tab metagame mode): the player's
    /// carried items as labeled elements. `Some` exactly in "use" mode.
    pub strip: Option<DebugUiPanel>,
    /// The item held on the cursor mid-drag (the original's "cursor IS the
    /// item", §2.4). `Some` between a lift and the place/throw that clears it.
    pub cursor: Option<DebugUiCursor>,
    /// The AMMOFULL ammo-cycle button (use mode + multi-ammo weapon wielded);
    /// clicking it cycles the wielded weapon's ammo type. `None` otherwise.
    pub ammo_cycle: Option<DebugUiElement>,
}

/// The item currently riding the cursor (a lifted inventory item): its runtime
/// entity id and symbolic name, so tests can assert lift/place/throw state.
#[derive(Debug, Serialize, Clone)]
pub struct DebugUiCursor {
    /// Runtime entity id of the held item (NOT stable across runs).
    pub entity_id: i32,
    pub label: Option<String>,
}

/// The open flat-mode MFD panel: which entity it is bound to and its element
/// list, so clients can click real widgets instead of hardcoding pixels.
#[derive(Debug, Serialize, Clone)]
pub struct DebugUiPanel {
    /// Runtime entity id of the bound object (NOT stable across runs).
    pub entity_id: i32,
    /// The bound object's `PropTemplateId` - stable across runs (the
    /// mission-file object id for level-authored entities). 0 if absent.
    pub template_id: i32,
    pub name: Option<String>,
    pub elements: Vec<DebugUiElement>,
}

/// One drawn element of the active panel. `label` gives clickable elements a
/// semantic identity (keypad digits "0"-"9", "clear", the host "close"
/// button, a loot item's name like "Psi Amp") so tests can click by meaning;
/// `rect` is on the 640x480 virtual canvas and `screen_rect` is the same rect
/// in normalized `[0,1]` screen coordinates (letterbox-corrected) - feed its
/// center straight to the `pointer.position` input channel.
#[derive(Debug, Serialize, Clone)]
pub struct DebugUiElement {
    /// "button" (clickable), "image", or "text".
    pub kind: String,
    pub texture: Option<String>,
    pub text: Option<String>,
    pub label: Option<String>,
    /// For entity-bound elements (loot-panel items): the item's runtime
    /// entity id (NOT stable across runs).
    pub entity_id: Option<i32>,
    /// Canvas-space rect `[x, y, w, h]` (640x480 virtual canvas).
    pub rect: [f32; 4],
    /// Normalized screen-space rect `[x, y, w, h]`.
    pub screen_rect: [f32; 4],
}

/// Animation playback state + posed skeleton for one entity, sampled at the
/// current frame. Joint positions are world-space, so stepping the simulation
/// and diffing successive snapshots measures pose continuity directly (a
/// single-frame spike across many joints = a seam pop).
#[derive(Debug, Serialize, Clone)]
pub struct DebugAnimationState {
    pub entity_id: i32,
    /// Currently playing clip (queue head), `None` when the queue is empty.
    pub clip: Option<String>,
    pub frame: u32,
    pub num_frames: u32,
    pub looping: bool,
    /// Sub-frame time carried toward the next frame advance (seconds).
    pub remaining_time: f32,
    /// Clips queued behind the head, in play order.
    pub queue: Vec<DebugAnimationQueueEntry>,
    /// Clip whose final frame poses the skeleton while the queue is empty.
    pub last_clip: Option<String>,
    pub blend: Option<DebugAnimationBlend>,
    /// Entity world position / rotation (the pose the joints are composed with).
    pub position: [f32; 3],
    pub rotation: [f32; 4], // quaternion [x, y, z, w]
    /// World-space joint positions (fixed 40-slot skeleton; unused slots track
    /// the entity transform).
    pub joints: Vec<[f32; 3]>,
}

#[derive(Debug, Serialize, Clone)]
pub struct DebugAnimationQueueEntry {
    pub name: Option<String>,
    pub num_frames: u32,
    pub looping: bool,
}

/// An in-flight crossfade from a previous clip's pose.
#[derive(Debug, Serialize, Clone)]
pub struct DebugAnimationBlend {
    pub from_clip: Option<String>,
    pub from_frame: f32,
    pub duration: f32,
    pub elapsed: f32,
    /// Blend progress 0..1 (0 = fully the old pose).
    pub alpha: f32,
}

/// A level-transition trigger (a `TrapTripLevel` tripwire / bulkhead): where it
/// leads (`dest_level` + optional spawn `dest_loc`) and its world `position`, so
/// a tester can teleport into its volume and let the real trigger fire the
/// transition (rather than warping explicitly).
#[derive(Debug, Serialize, Clone)]
pub struct DebugTransition {
    pub entity_id: i32,
    pub name: Option<String>,
    pub dest_level: String,
    pub dest_loc: Option<i32>,
    pub position: [f32; 3],
}

/// Debug scene trait for remote debugging capabilities
///
/// This trait provides debugging and inspection capabilities for game scenes,
/// allowing remote control and analysis through the debug runtime HTTP API.
///
/// It is designed to be optionally implemented by scenes that support debugging,
/// such as Mission scenes during development and testing.
pub trait DebuggableScene {
    /// List entities in the scene, sorted by distance from player
    ///
    /// Returns a list of entity summaries with basic information suitable
    /// for debug listing. The results are sorted by distance from the player
    /// position to make nearby entities easier to find.
    ///
    /// # Arguments
    /// * `limit` - Optional maximum number of entities to return
    /// * `filter` - Optional name pattern filter (supports wildcards)
    ///
    /// # Returns
    /// Vector of entity summaries sorted by distance from player
    fn list_entities(&self, limit: Option<usize>, filter: Option<&str>) -> Vec<DebugEntitySummary>;

    /// Resolve a client-facing entity id back to the live `EntityId`.
    ///
    /// The entity endpoints expose ids as `EntityId::inner() as i32`, which
    /// keeps only the low 32 bits of the index part (the low 48 bits hold
    /// `index + 1`; the top 16 hold the generation). Reconstructing via
    /// `EntityId::from_inner(id as u64)` therefore yields a generation-0
    /// handle that is stale for any recycled slot. This looks up the live
    /// entity whose truncated id matches instead.
    ///
    /// # Returns
    /// The live `EntityId`, or None if no live entity matches
    fn resolve_entity_id(&self, id: i32) -> Option<EntityId>;

    /// Get detailed information about a specific entity
    ///
    /// Returns comprehensive entity information including properties, links,
    /// inheritance chain, and other debug-relevant data.
    ///
    /// # Arguments
    /// * `id` - Entity ID to inspect
    ///
    /// # Returns
    /// Detailed entity information, or None if entity doesn't exist
    fn entity_detail(&self, id: EntityId) -> Option<DebugEntityDetail>;

    /// Animation playback state + world-space posed skeleton for an entity
    ///
    /// Returns None when the entity has no animation player (non-animated
    /// entities). See [`DebugAnimationState`].
    fn animation_state(&self, id: EntityId) -> Option<DebugAnimationState>;

    /// Perform a physics raycast for debugging
    ///
    /// Executes a raycast using the scene's physics system with full collision
    /// group support. Results include hit information and entity details.
    ///
    /// # Arguments
    /// * `start` - Ray starting position in world coordinates
    /// * `end` - Ray ending position (direction and distance calculated from start)
    /// * `mask` - Collision groups to test against
    ///
    /// # Returns
    /// Raycast hit result with entity and collision information
    fn raycast(&self, start: Point3<f32>, end: Point3<f32>, mask: RaycastMask) -> DebugRayHit;

    /// Teleport the player to a specific position
    ///
    /// Moves the player entity to the specified world coordinates. This is
    /// useful for testing different areas of the level and debugging
    /// position-dependent behavior.
    ///
    /// # Arguments
    /// * `position` - Target position in world coordinates
    ///
    /// # Returns
    /// Ok(()) on success, or error message if teleportation fails
    fn teleport_player(&mut self, position: Vector3<f32>) -> Result<(), String>;

    /// Move the player toward `target` in a single bounded, collision-validated
    /// hop.
    ///
    /// Unlike [`teleport_player`](Self::teleport_player), which warps the player
    /// unconditionally, this clamps the displacement to a maximum distance and
    /// shape-casts the player collider along the way, stopping short of any
    /// geometry it hits. Intended for automated navigation that must stay inside
    /// the level (a closed door, for instance, blocks the move).
    ///
    /// # Arguments
    /// * `target` - Desired destination in world coordinates
    ///
    /// # Returns
    /// A [`MoveResult`](crate::physics::MoveResult) describing how far the
    /// player actually moved and whether it was blocked.
    fn move_player(&mut self, target: Vector3<f32>) -> crate::physics::MoveResult;

    /// Get the current player position for distance calculations
    ///
    /// Returns the player's current world position, used for sorting
    /// entities by distance and other spatial queries.
    ///
    /// # Returns
    /// Player position in world coordinates
    fn player_position(&self) -> Vector3<f32>;

    /// List physics rigid bodies in the scene
    ///
    /// Returns a list of physics body summaries with basic information
    /// suitable for debug listing. Includes position, velocity, and
    /// associated entity information.
    ///
    /// # Arguments
    /// * `limit` - Optional maximum number of bodies to return
    ///
    /// # Returns
    /// Vector of physics body summaries
    fn list_physics_bodies(&self, limit: Option<usize>) -> Vec<DebugPhysicsBodySummary>;

    /// Get detailed information about a specific physics body
    ///
    /// Returns comprehensive physics body information including mass,
    /// inertia, damping, collision groups, and contact information.
    ///
    /// # Arguments
    /// * `body_id` - Physics body handle/ID to inspect
    ///
    /// # Returns
    /// Detailed physics body information, or None if body doesn't exist
    fn physics_body_detail(&self, body_id: u32) -> Option<DebugPhysicsBodyDetail>;

    /// Quality/settle metrics for every active ragdoll, for the verification
    /// harness (settle speeds, floor penetration, non-adjacent interpenetration,
    /// drift). Empty when the scene has no ragdolls.
    fn ragdoll_metrics(&self) -> Vec<DebugRagdollMetrics> {
        Vec::new()
    }

    /// Every impulse + multibody joint with its anchor separation (+ applied
    /// impulse for impulse joints), for ragdoll diagnostics. Empty when the
    /// scene has no joints.
    fn list_physics_joints(&self) -> Vec<DebugPhysicsJoint> {
        Vec::new()
    }

    /// Apply a world-space impulse to a dynamic physics body by `body_id`
    /// (waking it if asleep). Debug hook for poking ragdolls headlessly - e.g.
    /// verify a sleeping corpse wakes on impact. False = no such dynamic body.
    fn apply_body_impulse(&mut self, _body_id: u32, _impulse: [f32; 3]) -> bool {
        false
    }

    /// Colliders whose world AABB is malformed (NaN/inf, degenerate, or
    /// extreme). Empty means the level's collider geometry is clean. Used to
    /// diagnose physics-query misbehavior (bad raycasts, parry3d overflow).
    fn audit_colliders(&self) -> Vec<DebugColliderIssue> {
        Vec::new()
    }

    /// Snapshot of quest bits (objective flags) the game has set, for verifying
    /// mission progress. Empty when the scene has no quest state.
    fn quest_bits(&self) -> Vec<DebugQuestBit> {
        Vec::new()
    }

    /// Set a quest bit (objective flag) - for test setup / skipping ahead.
    /// `value` is "unknown", "incomplete", or "complete". Default: unsupported.
    fn set_quest_bit(&mut self, _name: &str, _value: &str) -> Result<(), String> {
        Err("scene does not support quest bits".to_string())
    }

    /// The items the player is carrying (backpack contents plus the hand-held
    /// items), for verifying pickups. Empty when the scene has no player.
    fn player_inventory(&self) -> Vec<DebugInventoryItem> {
        Vec::new()
    }

    /// The flat-mode UI state (`GET /v1/ui`): current mode ("shooter"/"use"),
    /// the open MFD panel, and the use-mode inventory strip, if any.
    /// Default: shooter, no panel, no strip (scenes without a flat metagame
    /// UI).
    fn ui_state(&self) -> DebugUiState {
        DebugUiState {
            mode: "shooter".to_string(),
            active_panel: None,
            strip: None,
            cursor: None,
            ammo_cycle: None,
        }
    }

    /// Put an existing world entity into the player's inventory (a headless
    /// "pick up" for testing). Models a pickup - the item lands in the backpack;
    /// wielding is a separate, presentation-specific concern. Default:
    /// unsupported.
    fn give_item(&mut self, _entity_id: EntityId) -> Result<(), String> {
        Err("scene does not support giving items".to_string())
    }

    /// Level-transition triggers in this scene (where each leads + its position),
    /// so a tester can follow the real triggers between levels instead of warping
    /// explicitly. Empty when the scene has none.
    fn list_transitions(&self) -> Vec<DebugTransition> {
        Vec::new()
    }

    /// Get current input context state
    ///
    /// Returns the current input state including head rotation, hand positions,
    /// and controller values. Used for debugging input issues and understanding
    /// current control state.
    ///
    /// # Returns
    /// Current input context state as a serializable structure
    fn get_input_state(&self) -> crate::input_context::InputContext;

    /// Set or modify input context values
    ///
    /// Allows remote control of input channels for testing and debugging.
    /// Can be used to simulate controller input, head rotation, and hand positions
    /// without requiring physical VR hardware.
    ///
    /// # Arguments
    /// * `channel` - Input channel to modify (e.g., "head.rotation", "left_hand.trigger_value")
    /// * `value` - New value for the channel (format depends on channel type)
    ///
    /// # Returns
    /// true if the channel was successfully modified, false if channel doesn't exist
    ///
    /// # Examples
    /// - `set_input("head.rotation", [0.0, 0.707, 0.0, 0.707])` - Set head rotation
    /// - `set_input("right_hand.trigger_value", 1.0)` - Full trigger press
    /// - `set_input("left_hand.thumbstick", [0.5, -0.8])` - Thumbstick input
    fn set_input(&mut self, channel: &str, value: serde_json::Value) -> bool;

    /// Get the current pathfinding test status
    ///
    /// Returns the state of the interactive pathfinding test system, so
    /// remote clients (e.g. the debug runtime) can verify that triggered
    /// pathfinding actions actually executed.
    fn pathfinding_test_status(&self) -> DebugPathfindingTestStatus;

    /// Inject a script message into a specific entity.
    ///
    /// Queues the message for delivery on the next scene update, letting debug
    /// clients exercise script behaviors (damage, frob, AI signals) without a
    /// physical interaction in the world. Returns `true` if the entity is alive
    /// and the message was queued.
    fn send_entity_message(&mut self, id: EntityId, message: DebugEntityMessage) -> bool;

    /// Monotonic pathfinding query counters (None when the scene has no
    /// pathfinding data). Remote clients diff snapshots across steps to
    /// measure per-frame query load and verify the frame budget.
    fn pathfinding_stats(&self) -> Option<DebugPathfindingStats> {
        None
    }

    /// The latest path each AI computed (empty when the scene has no
    /// pathfinding data or no AI has pathed yet). Lets remote clients see
    /// where every AI is trying to go and whether its route succeeded.
    fn ai_paths(&self) -> Vec<DebugAiPathEntry> {
        Vec::new()
    }
}

/// One AI's most recent path query, for debug introspection
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DebugAiPathEntry {
    /// EntityId::inner() as i32 - the same id space as the entity endpoints
    pub entity_id: i32,
    /// Where the AI was trying to go
    pub goal: [f32; 3],
    /// "Full" (route reaches the goal), "Partial" (goal unreachable; routed
    /// to the closest reachable point), or "Failed" (no route at all)
    pub outcome: String,
    /// Waypoints of the computed route (empty for Failed)
    pub waypoints: Vec<[f32; 3]>,
    /// Index of the waypoint the steering is CURRENTLY following (its live
    /// path may lag the latest computed route above)
    pub live_next_waypoint: Option<usize>,
    /// Length of the live path being followed
    pub live_path_len: Option<usize>,
    /// World position currently steered toward
    pub live_target: Option<[f32; 3]>,
    /// Seconds without progress toward the current waypoint
    pub live_stall_seconds: Option<f32>,
}

/// Snapshot of the pathfinding service's monotonic query counters.
///
/// Counts every find_path caller - including unbudgeted ones like the
/// interactive pathfinding test - so per-frame deltas can exceed the AI
/// frame budget while those are active.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DebugPathfindingStats {
    pub queries: u64,
    pub stressed_retries: u64,
    pub no_route: u64,
}

/// A script message a debug client can inject into a specific entity.
///
/// This is intentionally a small, serde-friendly subset of the engine's full
/// `MessagePayload` enum, surfaced so remote clients (HTTP / SDK) can exercise
/// script behaviors directly without simulating a world interaction. Extend it
/// as new debug scenarios need more message kinds.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum DebugEntityMessage {
    /// Deal `amount` damage (drives `InternalSimpleHealth` / AI health).
    /// `direction` (world-space, need not be normalized) and `point` optionally
    /// describe the blow so a death ragdoll reacts to it - same data a real
    /// projectile hit carries. Omitted = directionless damage.
    Damage {
        amount: f32,
        #[serde(default)]
        direction: Option<[f32; 3]>,
        #[serde(default)]
        point: Option<[f32; 3]>,
    },
    /// Frob (use) the entity.
    Frob,
    /// Send a named AI signal.
    Signal { name: String },
    /// Force an AI's alertness level (clamped by its alert cap).
    SetAlertness {
        level: dark::properties::AIAlertLevel,
    },
    /// Switch-link activate (what a tripwire/button sends to its targets).
    TurnOn,
    /// Switch-link deactivate.
    TurnOff,
}

/// Status of the interactive pathfinding test system
#[derive(Debug, Clone)]
pub struct DebugPathfindingTestStatus {
    /// Current state: "WaitingForStart", "WaitingForGoal", or "ShowingPath"
    pub state: String,
    /// Number of waypoints in the computed test path (0 if no path computed)
    pub test_path_waypoints: usize,
}
