import assert from "node:assert/strict";
import { test } from "node:test";
import { mkdir, writeFile } from "node:fs/promises";
import { GameServer, type UiElement } from "../src/index.js";
import { aimVrHandAt, aimVrHandAtCanvas } from "./helpers/vr-hand.js";
import { clickUiElement, canvasCenter, requirePanelPose } from "./helpers/ui.js";
import { ammoOf } from "./helpers/weapon.js";
test("VR dual ammo controls bind to the selected real held entity", { skip: process.env.SHOCK2_E2E !== "1", timeout: 180000 }, async () => {
    await using game = await GameServer.launch({ mission: "debug_interactions", debugFlags: ["--vr"] });
    await game.step({ frames: 30 });
    const rack = (await game.entities.list()).entities;
    const pistol = rack.find(e => e.template_id === -17)!;
    const shotgun = rack.find(e => e.template_id === -19)!;
    assert.ok(pistol && shotgun);
    for (const [hand, weapon, field] of [["right", pistol, "right_hand_entity_id"], ["left", shotgun, "wielded_entity_id"]] as const) {
        await aimVrHandAt(game, weapon.position, .2, 1, 0, { hand });
        assert.equal((await game.info()).player[field], weapon.id);
        await game.input.set(`${hand}_hand.position`, [hand === "left" ? -.7 : .7, .8, -.2]);
        await game.input.set(`${hand}_hand.rotation`, [0, 0, 0, 1]);
        await game.step({ frames: 3 });
    }
    await game.input.set("head.rotation", [0, 0, 0, 1]);
    await game.step({ frames: 60 });
    await game.input.trigger("ToggleUseMode");
    await game.step({ frames: 5 });
    const capture = async (name: string) => { const out = process.env.ASTRA_DUAL_AMMO_CAPTURE; if (!out)
        return; await mkdir(out, { recursive: true }); await game.screenshot(`${out}/vr-${name}.png`, 1600); await writeFile(`${out}/vr-${name}.json`, JSON.stringify({ ui: await game.ui.state(), info: await game.info(), pistol: await game.entities.detail(pistol.id), shotgun: await game.entities.detail(shotgun.id) }, null, 2)); };
    const click = async (e: UiElement) => { for (const trigger of [0, 1, 0]) {
        await aimVrHandAtCanvas(game, requirePanelPose(await game.ui.state()), canvasCenter(e), { hand: "right", squeeze: 1, trigger });
        await game.step({ frames: 3 });
    } };
    const arm = async (hand: string) => { const e = (await game.ui.state()).strip!.elements.find(e => e.label === `${hand} hand`); assert.ok(e); return e; };
    const control = async (label: string, target: number) => { const e = (await game.ui.state()).readout.find(e => e.label === label); assert.ok(e, label); assert.equal(e.entity_id, target, `${label} binds selected entity`); return e; };
    const ammo = async (id: number) => ammoOf(await game.entities.detail(id));
    assert.equal(await ammo(pistol.id), 12);
    assert.equal(await ammo(shotgun.id), 6);
    await control("reload", pistol.id);
    await capture("dual-right");
    await click(await arm("Left"));
    const initialShotgunMode = (await control("gun_setting", shotgun.id)).text;
    await click(await arm("Right"));
    await click(await control("gun_setting", pistol.id));
    const setting = (await game.ui.state()).active_panel!.elements.find(e => e.label === "setting_1");
    assert.ok(setting);
    const pistolSetting = (await control("gun_setting", pistol.id)).text;
    await click(setting);
    assert.notEqual((await control("gun_setting", pistol.id)).text, pistolSetting);
    await capture("pistol-setting");
    await click(await arm("Left"));
    assert.equal((await game.ui.state()).active_panel, null, "selecting another arm closes stale settings");
    await control("reload", shotgun.id);
    await capture("dual-left");
    const shotgunMode = await control("gun_setting", shotgun.id);
    assert.equal(shotgunMode.text, initialShotgunMode, "pistol burst mode leaves shotgun setting unchanged");
    await click(shotgunMode);
    assert.ok((await game.ui.state()).active_panel);
    await click(await control("cycle_ammo", shotgun.id));
    assert.equal(await ammo(shotgun.id), 0);
    assert.equal(await ammo(pistol.id), 12);
    await click(await control("cycle_ammo", shotgun.id));
    await click(await control("reload", shotgun.id));
    await game.step({ frames: 10 });
    assert.equal(await ammo(shotgun.id), 6, "selected shotgun reloads its ejected shells");
    assert.equal(await ammo(pistol.id), 12);
    await capture("shotgun-reloaded");
    await click(await arm("Right"));
    await click(await control("gun_setting", pistol.id));
    const unload = (await game.ui.state()).active_panel!.elements.find(e => e.label === "unload");
    assert.ok(unload);
    await click(unload);
    await game.step({ frames: 5 });
    assert.equal(await ammo(pistol.id), 0);
    assert.equal(await ammo(shotgun.id), 6);
    await click(await control("reload", pistol.id));
    await game.step({ frames: 10 });
    assert.equal(await ammo(pistol.id), 12);
    assert.equal(await ammo(shotgun.id), 6);
    await game.input.set("left_hand.squeeze", 1);
    await game.input.set("right_hand.squeeze", 1);
    await game.input.trigger("ToggleUseMode");
    await game.step({ frames: 3 });
    await game.input.set("right_hand.squeeze", 0);
    await game.step({ frames: 5 });
    assert.equal((await game.info()).player.right_hand_entity_id, null);
    await game.input.trigger("ToggleUseMode");
    await game.step({ frames: 5 });
    await control("reload", shotgun.id);
    await capture("drop-fallback");
    await game.input.set("left_hand.squeeze", 1);
    await game.input.trigger("ToggleUseMode");
    await game.step({ frames: 3 });
    const amp = (await game.entities.list()).entities.find(e => e.template_id === -247);
    assert.ok(amp);
    await aimVrHandAt(game, amp.position, .2, 1, 0, { hand: "right" });
    assert.equal((await game.info()).player.right_hand_entity_id, amp.id);
    await game.input.set("head.rotation", [0, 0, 0, 1]);
    await game.input.trigger("ToggleUseMode");
    await game.step({ frames: 5 });
    await click(await arm("Right"));
    const psi = (await game.ui.state()).readout.filter(e => e.label?.startsWith("psi_"));
    assert.ok(psi.length > 0);
    assert.ok(psi.every(e => e.entity_id === amp.id));
    assert.match((await arm("Right")).text ?? "", /: PSI$/);
    await capture("gun-psi");
});
test("Flat ammo selection maps the internal wield slot onto the visible right arm", { skip: process.env.SHOCK2_E2E !== "1", timeout: 90000 }, async () => {
    await using game = await GameServer.launch({ mission: "debug_weapons" });
    await game.step({ frames: 30 });
    await game.input.trigger("DebugCycleWeapon");
    await game.step({ frames: 10 });
    await game.input.trigger("ToggleUseMode");
    await game.step({ frames: 5 });
    const id = (await game.info()).player.wielded_entity_id;
    assert.ok(id != null);
    const ui = await game.ui.state();
    const right = ui.strip!.elements.find(e => e.label === "Right hand");
    assert.ok(right);
    assert.equal(right.entity_id, id);
    await clickUiElement(game, right);
    assert.equal((await game.ui.state()).readout.find(e => e.label === "reload")?.entity_id, id);
    const out = process.env.ASTRA_DUAL_AMMO_CAPTURE;
    if (out) {
        await mkdir(out, { recursive: true });
        await game.screenshot(`${out}/flat-wield.png`, 1600);
        await writeFile(`${out}/flat-wield.json`, JSON.stringify({ ui: await game.ui.state(), info: await game.info() }, null, 2));
    }
});
