import assert from "node:assert/strict";
import { test } from "node:test";
import { GameServer } from "../src/index.js";
import { aimVrHandAt, quatConjugate, quatRotate, sub } from "./helpers/vr-hand.js";

const enabled = process.env.SHOCK2_E2E === "1";
test("VR rapier extends on draw, fades its attached hum, and retracts in its holster", { skip: !enabled, timeout: 180_000 }, async () => {
  await using game = await GameServer.launch({ mission: "debug_interactions", debugFlags: ["--vr"] });
  await game.step({ frames: 30 });
  const [item] = await game.entities.byTemplate(-24);
  assert.ok(item);
  await aimVrHandAt(game, item.position, 0.2, 1);
  await game.step({ frames: 3 });
  let p = (await game.info()).player;
  assert.equal(p.right_hand_entity_id, item.id);
  let state = p.hand_feedback!.rapiers?.find(r => r.entity_id === item.id);
  assert.ok(state && state.extension > 0 && state.extension < 1, "draw should visibly extend over time");
  const handle = state.hum_handle;
  assert.ok(handle != null);
  await game.step({ frames: 20 });
  p = (await game.info()).player;
  state = p.hand_feedback!.rapiers!.find(r => r.entity_id === item.id)!;
  assert.equal(state.extension, 1);
  assert.equal(state.hum_handle, handle, "hum must not restart every frame");
  const hums = (await game.audio.recent()).sounds.filter(s => /^esloop/i.test(s.sample));
  assert.equal(hums.length, 1);
  assert.ok((await game.audio.loops()).loops.some(loop => loop.handle === handle), "hum must be a live repeating sink");
  assert.equal(hums[0]!.source_entity?.template_id, -24);
  assert.ok(p.hand_feedback!.haptics!.sequence[1] > 0);
  const center = p.hand_feedback!.holsters!.centers![0];
  const local = quatRotate(quatConjugate(p.rotation), sub(center, p.position));
  await game.input.set("right_hand.position", local);
  await game.step({ frames: 10 });
  await game.input.set("right_hand.squeeze", 0);
  await game.step({ frames: 3 });
  p = (await game.info()).player;
  assert.equal(p.hand_feedback!.holsters!.items[0], item.id);
  state = p.hand_feedback!.rapiers!.find(r => r.entity_id === item.id)!;
  assert.ok(state.extension > 0 && state.extension < 1 && !state.held);
  await game.step({ frames: 20 });
  p = (await game.info()).player;
  assert.ok(!p.hand_feedback!.rapiers!.some(r => r.entity_id === item.id));
  assert.ok(!(await game.audio.loops()).loops.some(loop => loop.handle === handle));
  const stopped = (await game.audio.recent()).sounds.find(s => s.handle === handle)!;
  assert.ok(stopped.stopped_at_sim_time != null, "stowing must stop the hum after fading");
  await game.input.set("right_hand.squeeze", 1);
  await game.step({ frames: 20 });
  p = (await game.info()).player;
  assert.equal(p.right_hand_entity_id, item.id, "draw keeps the same inventory entity");
  assert.equal(p.hand_feedback!.rapiers!.find(r => r.entity_id === item.id)!.extension, 1);
  assert.equal((await game.audio.recent()).sounds.filter(s => /^esloop/i.test(s.sample)).length, 2);
});
