import assert from "node:assert/strict";
import { test } from "node:test";
import { GameServer } from "../src/index.js";
import { aimVrHandAt, aimVrHandAtCanvas, quatConjugate, quatRotate, sub } from "./helpers/vr-hand.js";
import { ammoOf } from "./helpers/weapon.js";

const enabled = process.env.SHOCK2_E2E === "1";
type Hand = "left" | "right";
const owner = (hand: Hand) => hand === "left" ? "wielded_entity_id" : "right_hand_entity_id";
async function reach(game: GameServer, hand: Hand, slot: number, holster = false) {
  const player = (await game.info()).player;
  const center = (holster ? player.hand_feedback?.holsters : player.hand_feedback?.shoulder_backpack)?.centers?.[slot];
  assert.ok(center);
  await game.input.set(`${hand}_hand.position`, quatRotate(quatConjugate(player.rotation), sub(center, player.position)));
  await game.step({ frames: 5 });
}
const remembered = async (game: GameServer) => (await game.info()).player.hand_feedback?.body_gear?.shoulder_weapons;

test("large weapons refuse thigh storage and recall independently from either shoulder", { skip: !enabled, timeout: 180_000 }, async () => {
  await using game = await GameServer.launch({ mission: "debug_interactions", debugFlags: ["--vr"] });
  await game.step({ frames: 30 });
  const rack = (await game.entities.list()).entities;
  const shotgun = rack.find(e => e.template_id === -19)!;
  const pistol = rack.find(e => e.template_id === -17)!;
  await aimVrHandAt(game, shotgun.position, 0.2, 1);
  await game.step({ frames: 5 });
  const ammo = ammoOf(await game.entities.detail(shotgun.id));
  await reach(game, "right", 0, true);
  await game.input.set("right_hand.squeeze", 0);
  await game.step({ frames: 8 });
  assert.equal((await game.info()).player.right_hand_entity_id, shotgun.id, "refusal retains shotgun");
  assert.equal((await game.info()).player.hand_feedback?.holsters?.items[0], null);
  await game.input.set("right_hand.squeeze", 1);
  await reach(game, "right", 1);
  await game.input.set("right_hand.squeeze", 0);
  await game.step({ frames: 8 });
  assert.deepEqual(await remembered(game), [null, shotgun.id]);
  assert.equal((await game.info()).player.right_hand_entity_id, null);
  assert.equal((await game.physics.bodies({entityId: shotgun.id})).bodies.length, 0);
  await aimVrHandAt(game, pistol.position, 0.2, 1, 0, { hand: "left" });
  await reach(game, "left", 0);
  await game.input.set("left_hand.squeeze", 0);
  await game.step({ frames: 8 });
  assert.deepEqual(await remembered(game), [pistol.id, shotgun.id]);
  // The interface decorates the original inventory items, not duplicate slots.
  await game.input.trigger("ToggleUseMode");
  await game.step({ frames: 8 });
  const assignedUi = await game.ui.state();
  for (const [entity, label] of [[pistol.id, "Left shoulder"], [shotgun.id, "Right shoulder"]] as const) {
    const elements = assignedUi.strip!.elements.filter(e => e.entity_id === entity);
    assert.equal(elements.filter(e => e.kind === "button").length, 1);
    const badge = elements.find(e => e.label === label)!;
    assert.ok(badge, `${label} marks the original item`);
    await aimVrHandAtCanvas(game, assignedUi.panel_pose!, [badge.rect[0] + badge.rect[2] / 2, badge.rect[1] + badge.rect[3] / 2], { hand: "right", squeeze: 0 });
    await game.step({ frames: 2 });
    assert.ok((await game.ui.state()).name_strip!.startsWith(`${label}:`));
  }
  await game.input.trigger("ToggleUseMode");
  await game.step({ frames: 5 });
  // Cross-hand recall is based on the shoulder reached, not controller handedness.
  await reach(game, "left", 1);
  await game.input.set("left_hand.squeeze", 1);
  await game.step({ frames: 8 });
  assert.equal((await game.info()).player.wielded_entity_id, shotgun.id);
  assert.deepEqual(await remembered(game), [pistol.id, null]);
  assert.equal(ammoOf(await game.entities.detail(shotgun.id)), ammo);
  // Returning via the ordinary MFD preserves the shoulder assignment.
  await game.input.trigger("ToggleUseMode");
  await game.step({ frames: 5 });
  assert.equal((await game.ui.state()).strip!.elements.some(e => e.label === "Right shoulder"), false, "recalled weapon has no inventory badge");
  const panel = (await game.ui.state()).panel_pose!;
  await aimVrHandAtCanvas(game, panel, [320, 60], { hand: "left", squeeze: 1 });
  await game.step({ frames: 5 });
  await game.input.set("left_hand.squeeze", 0);
  await game.step({ frames: 8 });
  assert.equal((await game.info()).player.wielded_entity_id, null);
  assert.deepEqual(await remembered(game), [pistol.id, shotgun.id]);
  assert.ok((await game.ui.state()).strip!.elements.some(e => e.label === "Right shoulder" && e.entity_id === shotgun.id), "ordinary backpack return restores the badge");
  await game.input.trigger("ToggleUseMode");
  await game.step({ frames: 5 });
  await reach(game, "left", 1);
  await game.input.set("left_hand.squeeze", 1);
  await game.step({ frames: 8 });
  assert.equal((await game.info()).player.wielded_entity_id, shotgun.id);
  await reach(game, "right", 0);
  await game.input.set("right_hand.squeeze", 1);
  await game.step({ frames: 8 });
  assert.equal((await game.info()).player.right_hand_entity_id, pistol.id);
  assert.deepEqual(await remembered(game), [null, null]);
  await game.step({ frames: 30 });
  assert.equal((await game.info()).player.wielded_entity_id, shotgun.id);
  // Replacing a shoulder shortcut leaves the previous weapon in normal inventory.
  await game.input.set("left_hand.squeeze", 0);
  await game.input.set("right_hand.squeeze", 0);
  await game.step({ frames: 8 });
  assert.deepEqual(await remembered(game), [pistol.id, shotgun.id]);
  await game.input.set("right_hand.squeeze", 1);
  await game.step({ frames: 8 });
  await reach(game, "right", 1);
  await game.input.set("right_hand.squeeze", 0);
  await game.step({ frames: 8 });
  assert.deepEqual(await remembered(game), [null, pistol.id]);
  assert.equal((await game.player.inventory()).items.find(i => i.entity_id === shotgun.id)?.location, "inventory");
  await game.input.trigger("ToggleUseMode");
  await game.step({ frames: 8 });
  const reassigned = (await game.ui.state()).strip!.elements.filter(e => e.label === "Left shoulder" || e.label === "Right shoulder");
  assert.equal(reassigned.length, 1);
  assert.equal(reassigned[0].entity_id, pistol.id);
  assert.equal(reassigned[0].label, "Right shoulder");
});

test("shoulder weapon survives save/load and mission transition in the real backpack", { skip: !enabled, timeout: 240_000 }, async () => {
  await using game = await GameServer.launch({ mission: "medsci1.mis", debugFlags: ["--vr"] });
  await game.step({ frames: 5 });
  const spawned = await game.player.spawnItem(-19);
  await game.input.trigger("ToggleUseMode");
  await game.step({ frames: 5 });
  const ui = await game.ui.state();
  const cell = ui.strip?.elements.find(e => e.entity_id === spawned.entity_id);
  assert.ok(cell);
  await aimVrHandAtCanvas(game, ui.panel_pose!, [cell.rect[0]+cell.rect[2]/2, cell.rect[1]+cell.rect[3]/2], { hand: "right", squeeze: 1 });
  await game.step({ frames: 5 });
  await game.input.trigger("ToggleUseMode");
  await game.step({ frames: 5 });
  assert.equal((await game.info()).player.right_hand_entity_id, spawned.entity_id);
  const ammo = ammoOf(await game.entities.detail(spawned.entity_id));
  await reach(game, "right", 1);
  await game.input.set("right_hand.squeeze", 0);
  await game.step({ frames: 8 });
  const name = `shoulder-recall-${Date.now()}`;
  await game.save(name);
  await game.load(name);
  await game.step({ frames: 8 });
  const restored = (await remembered(game))?.[1];
  assert.ok(restored != null);
  assert.equal(ammoOf(await game.entities.detail(restored)), ammo);
  await game.transitionLevel("medsci2.mis");
  await game.step({ frames: 8 });
  const moved = (await remembered(game))?.[1];
  assert.ok(moved != null);
  assert.equal((await game.player.inventory()).items.find(i => i.entity_id === moved)?.location, "inventory");
  await reach(game, "left", 1);
  await game.input.set("left_hand.squeeze", 1);
  await game.step({ frames: 8 });
  assert.equal((await game.info()).player[owner("left")], moved);
  assert.equal(ammoOf(await game.entities.detail(moved)), ammo);
});
