name: Build Android

on:
  push:
    branches: ["**"]
    paths-ignore:
      - '**/*.md'
  # Not needed with wildcard branches
  # pull_request:
  #   branches: ["main"]
  #   paths-ignore:
  #     - '**/*.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test release version stamping
        run: python3 -m unittest discover -s .github/scripts -p 'test_*.py'

      - uses: ./.github/actions/setup-android

      # Actual build steps
      - name: Build Android APK
        run: cargo apk build
        working-directory: runtimes/oculus_runtime
