name: Build & Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
  
    # Install Linux-specific dependencies
    - name: Install ALSA (Linux only)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev

    # Install Windows-specific dependencies
    - name: Install CMake (Windows only)
      if: runner.os == 'Windows'
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      
    - name: Build
      run: cargo build --verbose --release
      working-directory: runtimes/desktop_runtime
    - name: Run tests
      run: cargo test --verbose
      working-directory: runtimes/desktop_runtime
